import type { Metadata } from "next";
import RQProvider from "@/shared/component/RQProvider";

import "./ui/globals.css";
import Navbar from "./ui/shared/navbar/navbar";
import Footer from "./ui/shared/footer/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RQProvider>
          <div className="flex flex-col justify-between h-screen p-[20px]">
            <div>
              <Navbar />
              {children}
              <Footer />
            </div>
          </div>
        </RQProvider>
      </body>
    </html>
  );
}
